export const GET_FETCH_WEATHER_BY_CITY = 'GET_FETCH_WEATHER_BY_CITY';
export const GET_WEATHER_BY_CITY_SUCCESS = 'GET_WEATHER_BY_CITY_SUCCESS';
export const GET_WEATHER_BY_CITY_FAIL = 'GET_WEATHER_BY_CITY_FAIL';

