export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_FILTER = 'LOGIN_FILTER';
export const LOGIN_FILTER_SUCCESS = 'LOGIN_FILTER_SUCCESS';

export const LOGUOT = 'LOGUOT';

export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const UPDATE_CUSTOMERFT = 'UPDATE_CUSTOMERFT';
export const IMPORT_CUSTOMER = 'IMPORT_CUSTOMER';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const IMPORT_PRODUCTS = 'IMPORT_PRODUCTS';
export const UPDATE_PRODUCTSFT = 'UPDATE_PRODUCTSFT';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';

export const FETCH_INVOICES = 'FETCH_INVOICES';
export const UPDATE_INVOICESFT = 'UPDATE_INVOICESFT';
export const IMPORT_INVOICES = 'IMPORT_INVOICES';

export const FETCH_SUPLIERS = 'FETCH_SUPLIERS';
export const UPDATE_SUPLIERSFT = 'UPDATE_SUPLIERSFT';
export const IMPORT_SUPLIERS = 'IMPORT_SUPLIERS';

export const GETSTUDY = 'GETSTUDY';
export const RANDOMSTUDY = 'RANDOMSTUDY';
export const GETALLSTUDY = 'GETALLSTUDY';
export const CREATEMULTIPLE = 'CREATEMULTIPLE';
export const ONNEXTSTUDY = 'ONNEXTSTUDY';
export const ONNEXTSTUDYYES = 'ONNEXTSTUDYYES';
export const ONSETNUMBERSTUDY = 'ONSETNUMBERSTUDY';

export const GETSUBJECT = 'GETSUBJECT';
export const RANDOMSUBJECT = 'RANDOMSUBJECT';
export const GETALLSUBJECT = 'GETALLSUBJECT';
export const CREATEMULTIPLESJ = 'CREATEMULTIPLESJ';
export const ONNEXTSUBJECT = 'ONNEXTSUBJECT';
export const ONNEXTSUBJECTYES = 'ONNEXTSUBJECTYES';
export const ONSETNUMBERSUBJECT = 'ONSETNUMBERSUBJECT';
export const SETSELECT = 'SETSELECT';
